export const SCOPENAME = 'module:polls';

// info
export const GET_POLL = `${SCOPENAME}/GET_POLL`;
export const GET_POLL_BY_HEIGHT = `${SCOPENAME}/GET_POLL_BY_HEIGHT`;
export const SET_POLL = `${SCOPENAME}/SET_POLL`;

export const GET_POLL_VOTES = `${SCOPENAME}/GET_POLL_VOTES`;
export const SET_POLL_VOTES = `${SCOPENAME}/SET_POLL_VOTES`;

export const GET_WALLECT_ACCOUNTS = `${SCOPENAME}/GET_WALLECT_ACCOUNTS`;
export const SET_WALLECT_ACCOUNTS = `${SCOPENAME}/SET_WALLECT_ACCOUNTS`;


// list
export const GET_POLL_LIST = `${SCOPENAME}/GET_POLL_LIST`;
export const SET_POLL_LIST = `${SCOPENAME}/SET_POLL_LIST`;

export const GET_POLL_LIST_REQUEST = `${SCOPENAME}/GET_POLL_LIST_REQUEST`;
export const GET_POLL_LIST_SUCCESS = `${SCOPENAME}/GET_POLL_LIST_SUCCESS`;
export const GET_POLL_LIST_FAILURE = `${SCOPENAME}/GET_POLL_LIST_FAILURE`;