export const SCOPENAME = 'module:proposals';

// info
export const GET_PROPOSAL = `${SCOPENAME}/GET_PROPOSAL`;
export const GET_PROPOSAL_BY_HEIGHT = `${SCOPENAME}/GET_PROPOSAL_BY_HEIGHT`;
export const SET_PROPOSAL = `${SCOPENAME}/SET_PROPOSAL`;

// list
export const GET_PROPOSAL_LIST = `${SCOPENAME}/GET_PROPOSAL_LIST`;
export const SET_PROPOSAL_LIST = `${SCOPENAME}/SET_PROPOSAL_LIST`;

export const GET_PROPOSAL_LIST_REQUEST = `${SCOPENAME}/GET_PROPOSAL_LIST_REQUEST`;
export const GET_PROPOSAL_LIST_SUCCESS = `${SCOPENAME}/GET_PROPOSAL_LIST_SUCCESS`;
export const GET_PROPOSAL_LIST_FAILURE = `${SCOPENAME}/GET_PROPOSAL_LIST_FAILURE`;